parser: "@typescript-eslint/parser"
env:
  browser: true
  commonjs: true
  es6: true
  jest: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - prettier
  - plugin:jsx-a11y/strict

plugins:
  - react-hooks

settings:
  react:
    version: detect

rules:
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/explicit-function-return-type": off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  react/prop-types: off
