[build]
	base = "."
	publish = "out"
	command = "./ci/netlify-deploy.sh"

[[redirects]]
  from = "/websocket*"
  to = "/websocket.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = "200!"
