version: 2
jobs:
  fmt:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - dependencies-
      - run: sudo -E yarn fmt
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependencies-{{ checksum "yarn.lock" }}

  lint:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - dependencies-
      - run: sudo -E yarn lint
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - dependencies-
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  fmt:
    jobs:
      - fmt
  lint:
    jobs:
      - lint
  test:
    jobs:
      - test
