version: 2
jobs:
  ci:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found.
            - dependencies-
      - run: sudo -E yarn ci
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  ci:
    jobs:
      - ci
