name: ci
on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v1
      - run: yarn && yarn fmt
        env:
          CI: 1

  lint:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v1
      - run: yarn && yarn lint
        env:
          CI: 1

  test:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v1
      - run: yarn && yarn test
      - uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
